### ISSUE TITLE
图形卡被识别为Intel 500，显存只有7m，这个要怎么解？cpu是i7 8650u的那一款

### ISSUE THREAD

**Issue by 2276193373** [dbv/hackintosh_redmibook#1]

**Comment by 2276193373** [comment]
cpu是i7 8650u的那一款

**Comment by dbv** [comment]
EFI 用我的那个就能识别到1.5G 显存

https://github.com/dbv/redmibook_hackintsh_EFI/tree/master/EFI_redmibook_%E5%8F%AF%E7%94%A8/EFI

**Comment by 2276193373** [comment]
> EFI 用我的那个就能识别到1.5G 显存
> 
> https://github.com/dbv/redmibook_hackintsh_EFI/tree/master/EFI_redmibook_%E5%8F%AF%E7%94%A8/EFI

我换了你这个EFI后，显卡没问题了，但是现在没声音了，音量按钮是灰色的，偏好设置里也调不了，是不是声卡驱动出了问题，这个要怎么解决，请指教一二

**Comment by dbv** [comment]
你之前声卡有没有问题？如果没有问题的话 先把你之前的EFI发给我一份，我这里的EFI好像声卡是有问题。你的声卡驱动解决没有？

**Comment by 2276193373** [comment]
> 你之前声卡有没有问题？如果没有问题的话 先把你之前的EFI发给我一份，我这里的EFI好像声卡是有问题。你的声卡驱动解决没有？

我用那个完成度90%的EFI的声卡是没问题的，但是显卡显示7m，然后用上面你给的链接的EFI显卡没问题了，但是没声音了，23333。我想应该把两者结合一下就好了，可是我不会弄23333

**Comment by dbv** [comment]
你把你之前的EFI文件发给我，或则给个链接
331234958@qq.com

**Comment by dbv** [comment]
只要你把你的之前那份EFI给我。我就有办法解决声卡+显卡的问题

**Comment by dbv** [comment]
顺便留一个你的联系方式，微信或则什么的
